### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by jeongyunnim** [jeongyunnim/CPP_Module05#1]
- ex00
- [ ] 서브젝트에서 요구하는 수준의 test문 작성
- [ ] 클래스 exception 구현
- [ ] try/catch문 작성
- [ ] 삽입 연산자(<<) 오버로딩
